### ISSUE TITLE
Error messages above the form don't focus the input (also lots of "undefined" classnames)

### ISSUE THREAD

**Issue by pcraig3** [DTS-STN/Alpha-Site#140]
The error messages in the validation errors warning box at the top should either move focus to the field label or the input itself. We should also be using anchor links instead of buttons for the warning messages.

So it should look more or less like this:

```html
<ul data-cy="error-box-items">
  <li>
    <a href="#email">Error 1: Must be a valid email</a> 
    <!-- OR -->
    <a href="#email-label">Error 1: Must be a valid email</a> 
  </li>
</ul>

<form>
  <label for="email" id="email-label">Email address</label>
  <div class="validation-message">Error 1: Must be a valid email</div>
  <input type="text" id="email" />
</form>
```

Right now, we are using buttons not links, the ids are the full sentence instead of something more meaningful (ids shouldn't really have whitespace), and there are a lot of undefined values in the classname there.

<img width="1229" alt="Screen Shot 2021-06-27 at 15 02 30" src="https://user-images.githubusercontent.com/2454380/123556335-b513ce00-d758-11eb-9b57-893849cecb4c.png">

**Comment by will0684** [comment]
Addressed here: https://github.com/DTS-STN/Alpha-Site/pull/159
