### ISSUE TITLE
Documentation for adding a page to the Alpha Site

### ISSUE THREAD

**Issue by pcraig3** [DTS-STN/Alpha-Site#185]
Neil Mispelaar (@neilmispelaar) added a big comment to the "[Go-live Process for Non-coded Prototypes](https://014gc.sharepoint.com/:w:/s/DECD/ER-aUrcAPNNBhgzzmOHSUA8BDbTYoaQ9Lhi6dMmq8vmHPg?e=Sk0nyn)" document.

Specifically, it says 

> - Pages are a branch of the existing repo 
> - Please copy existing header, footer and report a problem widget 

Neil followed up with the following comment: 

> Some information that would be helpful:

- [x] Branch naming convention
- [x] Folder naming conventions
- [x] Do we create a folder for each experiment and put files in there or create a file under a general experiments folder
- [x] Page naming conventions
- [x] What is strategy around hosting assets like video files and images (should they exist in the project or do we have a CDN for them to enhance download speed)
- [x] Location of translation files and general strategy around internationalisation
- [x] Do the files need to be linted before submitting and any other acceptance criteria we should be aware of
- [x] Do you require any automated tests to be in place for the pages that we are adding
- [x] Do we need to link up the experiments page(s) that we created from anywhere within the project
- [x] Do you have deploy previews setup where we can test on a live domain and share preview links

I'll answer them in the comments below.

**Comment by pcraig3** [comment]
#### Branch naming convention

We don't really have one. Our branch names usually describe the feature (eg, `remove-user-no-gcnotify`) and are sometimes snake-case and sometimes camelCase.

#### Folder naming conventions

Pages are under the `/pages` folder. You can see existing pages (eg, "/about" or "/home") at "/pages/about.js" and "/pages/home.js", to give a couple of examples. We are using Next.js, so the official documentation is here: https://nextjs.org/docs/basic-features/pages

For the product descriptions, we should create a `/pages/projects` directory and then create product description pages in the `projects` directory.

The URL will mirror the directory structure and filename. So, for example, if you created a file `pages/projects/life-journeys.js`, then the URL would be http://localhost:3000/projects/life-journeys

#### Do we create a folder for each experiment and put files in there or create a file under a general experiments folder

Create a `/projects` folder under `/pages`.

#### Page naming conventions

We have been using one-word URLs most of the time. We have a `thankyou.js` page, not because we've thought too hard about it, but just because that's what we went with. I would say we don't really have conventions, but we prefer hyphens for multi-word URLs.

#### What is strategy around hosting assets like video files and images (should they exist in the project or do we have a CDN for them to enhance download speed)

Keep them in the repo. They are stored in the "/public" folder. We are using Next.js, so here are the official docs around static file serving: https://nextjs.org/docs/basic-features/static-file-serving

#### Location of translation files and general strategy around internationalisation

We use placeholders in our page files, and then the keys map to content in json files:
- EN: (/public/locales/en/common.json)[https://github.com/DTS-STN/Alpha-Site/blob/3a815c9f10cf5c60c5a7b4bb2ea02f3265fd483e/public/locales/en/common.json]
- FR: (/public/locales/fr/common.json)[https://github.com/DTS-STN/Alpha-Site/blob/3a815c9f10cf5c60c5a7b4bb2ea02f3265fd483e/public/locales/fr/common.json]

@will0684 can expand on this, if needed.

#### Do the files need to be linted before submitting and any other acceptance criteria we should be aware of

Yeah, we try to run `npm run lint` before committing.

#### Do you require any automated tests to be in place for the pages that we are adding

@will0684, do we?

#### Do we need to link up the experiments page(s) that we created from anywhere within the project

Yes, link them from the "Experiments" page (soon to be called the "Projects" page).

#### Do you have deploy previews setup where we can test on a live domain and share preview links

No, but when stuff is merged, it's auto-deployed. 

We do:
- Build it locally
- Submit a PR
- Other devs pull it down, build it locally themselves
- PR is approved
- Merge -> autodeploy

**Comment by neilmispelaar** [comment]
#### Folder naming conventions

May I recommend a folder for each experiment (just to confirm, are projects the same as experiments in the nomenclature)? This would be to 'contain' projects that require multiple pages.  

##### Pattern for project home page
```
\pages\projects\[name of project]\index
```

##### Example
```
\pages\projects\virtual-assistant\index
```

##### User experience
```
https://domain.ca/en/projects/virtual-assistant/[index]
```

##### Fun issue

The pattern above does not address French language requirements.

Ideally a more balanced approach to languages would provide both `en` and `fr` root experiences so as to not have english as a default language. 

##### Ideal user experience
```
https://domain.ca/en/projects/virtual-assistant/[index]
https://domain.ca/fr/projects/assistant-virtuel/[index]
```

**Comment by neilmispelaar** [comment]
#### Page naming conventions

Great to see that your preferred method is hyphens to separate multiple words in URLs. 

In a previous project, we did some SEO research and found that some large search engines at the time preferred a hyphenated approach to multi word URL names because it helped match user search key words. 

That being said - I'm not sure if Search Engines even consider URLs anymore when calculating page ranking.

**Comment by neilmispelaar** [comment]
#### What is strategy around hosting assets like video files and images (should they exist in the project or do we have a CDN for them to enhance download speed)

Would like to recommend a folder structure for the public folder area for project resources.

##### One example: 
```
\public
  \projects
    \[match project folder name]
      \images
      \videos
    \[a whole other project folder]
      \images
```

This way, if a project / experiment is removed you can wipe one folder and tidy up the repo fairly easily.

For performance, would have loved to have seen a CDN used for some files (perhaps maybe that's a future opportunity).

**Comment by neilmispelaar** [comment]
> Yes, link them from the "Experiments" page (soon to be called the "Projects" page).

Thanks for the clarification.

**Comment by neilmispelaar** [comment]
#### Location of translation files and general strategy around i18n

> We use placeholders in our page files, and then the keys map to content in json files:
> 
>     EN: /public/locales/en/common.json
>     FR: /public/locales/fr/common.json
> 

Does it make sense to put a project's specific translations in the common area?

Once again - thinking about a scenario where a project is removed - untangling all of the translations for that project could be less than fun. 

Perhaps translations for a project page make more sense in the content page or a separate file (outside of common).

**Comment by will0684** [comment]
@neilmispelaar You can create a new translation content namespace by creating a new json file in each locale folder named whatever you want that namespace to be: virtualConcierge.json for example, and load that namespace in getStaticProps of the pages you want those specific translations loaded into. The next-i18next readme talks a bit about it here: https://github.com/isaachinman/next-i18next

**Comment by neilmispelaar** [comment]
> @neilmispelaar You can create a new translation content namespace by creating a new json file in each locale folder named whatever you want that namespace to be: virtualConcierge.json for example…

This is perfect. Thank you for the info.

**Comment by neilmispelaar** [comment]
#### Do you have deploy previews setup where we can test on a live domain and share preview links

> No, but when stuff is merged, it's auto-deployed.

Would recommend these be investigated. They are super easy to setup on Netlify / similar and have been really invaluable when designers need to provide feedback on in progress development work as not everyone is familiar with running local `npm run dev`. 

<img width="1045" alt="Screen Shot 2021-07-13 at 4 29 46 PM" src="https://user-images.githubusercontent.com/9325038/125520509-70729468-0b2c-4510-afd7-b6d97703073b.png">

**Comment by pcraig3** [comment]
@neilmispelaar, I'm going to try to respond to them all in here

> May I recommend a folder for each experiment (just to confirm, are projects the same as experiments in the nomenclature)? This would be to 'contain' projects that require multiple pages.

Putting a file into the folder isn't a hard requirement, it's just easier that way (although, as you point out, it scales less well). I've added a new page in #201, so you can reference how that one is done. If you wanted to use a different folder structure, fill your boots.


> ##### Fun issue
> The pattern above does not address French language requirements.
> 
> ##### Ideal user experience
> ```
> https://domain.ca/en/projects/virtual-assistant/[index]
> https://domain.ca/fr/projects/assistant-virtuel/[index]
> ```

Good point, I did a little research here because a friend of mine at CDS was telling me that bilingual _path names_ are technically not required. 

In the TBS [Standard on Web Usability](https://www.tbs-sct.gc.ca/pol/doc-eng.aspx?id=24227) (Appendix B), it refers a number of times to "Primary domain names" but never to the URL path. 

<details>
<summary>Click to open image</summary>
<img width="750" alt="Screen Shot 2021-07-13 at 16 18 48" src="https://user-images.githubusercontent.com/2454380/126013872-1ce66895-bcf3-4cbe-be40-f9ce43939ed8.png">
</details>

Technically, this means we need to ensure the domain itself is bilingual, but the path is exempted.

So we could do something like this:
- https://hello.ca/about
- https://bonjour.ca/about?lang=fr

You're right to say that the way we handle translations doesn't work out of the box for bilingual pathnames. But I think it's okay to leave it be, and open this later as an issue if it is identified as a problem (it hasn't been so far).


> Great to see that your preferred method is hyphens to separate multiple words in URLs.
> That being said - I'm not sure if Search Engines even consider URLs anymore when calculating page ranking.

The Digital Center url is hyphenated, so now you can see that working. And yeah, I don't think URL paths are really weighted by search engines.

> Would like to recommend a folder structure for the public folder area for project resources.

The Digital Center images are all at the root level, namespaced with "dc-". You can create an internal directory structure in there if you like (eg, "public/projects/appname"), that will work fine.

> Perhaps translations for a project page make more sense in the content page or a separate file (outside of common).

Agreed, common translations files are way messier than grouping the images together, imo. I specific "dc.json" files for the Digital Channel content specifically. You can see how it's done in #201. Note that you have to call your translations using the name of the file as a namespace, so a short filename is probably better.

For example:
- If I created "digital-center.json" that looked like `{"h1": "PageTitle"}`, then I would call it in the application like this: `t("digital-channel:h1")`.
- If the filename is "dc.json", then I call it like this `t("dc:h1")`. 


> Would recommend [deploy previews] be investigated.

Yeah, I think deploy previews are really valuable and it would be good to have them. We use Heroku a lot at CDS for this.

The friction I've found around this is the double-whammy of 'everything should be assessed before we can use it (ie, pay for it)', and 'we don't trust SaaS/PaaS services out of principle'. At CDS we pay for Heroku and everyone knows we use it. Here, we could maybe get deploys up running for free with Netlify, but if someone found out about it, they wouldn't be happy. Essentially, it was/is just a fight I didn't want to have.

So I won't be pursuing this in my time here, but if you already have them or want to introduce them on any repos you are working on, you are more than welcome.

**Comment by pcraig3** [comment]
Closing this issue since we are done adding pages for the time being.
