### ISSUE TITLE
Splash page in mobile lansdcape has a disappearing FIP

### ISSUE THREAD

**Issue by neilmispelaar** [DTS-STN/Alpha-Site#191]
### Description of issue

- When you put the alpha site splash page in mobile landscape mode on safari the position of the content box is calculated using the height of the screen and so the FIP disappears off the page:

#### Screenshot
![IMG_4420](https://user-images.githubusercontent.com/9325038/125656034-2646536b-4933-4ec2-a021-59d2015d671d.PNG)

#### Canada.ca Splash page
![IMG_4421](https://user-images.githubusercontent.com/9325038/125656031-35a525c8-7e9b-4698-ae16-f080759cb31a.PNG)

**Comment by DaceyTom2** [comment]
VC fixed this by making the background fixed and the box margin auto. We used similar tailwind configuration so the vue template should match up nicely.
Example code https://github.com/Toad-Labs/vc-frontend-static/blob/main/src/views/Splash.vue

**Comment by neilmispelaar** [comment]
The Francais button is also missing the `lang="fr"` attribute for [WCAG 3.1.2 compliance](https://www.w3.org/WAI/WCAG21/Understanding/language-of-parts.html)

<img width="617" alt="Screen Shot 2021-07-14 at 11 47 28 PM" src="https://user-images.githubusercontent.com/9325038/125726067-cf001a51-8b83-4889-8493-4b2e2fc08930.png">
