### ISSUE TITLE
Robots.txt file in prod disallows indexing

### ISSUE THREAD

**Issue by pcraig3** [DTS-STN/Alpha-Site#331]
We want to make sure we're allowing indexing in production, but not on dev. 

For our dev site ([alphasite.dts-stn.com](https://alphasite.dts-stn.com)), we should see this:

```
User-agent: *
Disallow: /
```

[And we do](https://alphasite.dts-stn.com/robots.txt)! So that's great.

In production ([alpha.service.canada.ca](https://alpha.service.canada.ca)), we should see this:

```
User-agent: *
Allow: /
Disallow: /api
```

[But we don't](https://alpha.service.canada.ca/robots.txt). Instead, we see the same as the dev site.

So it's kind of 2 things to resolve this issue:

1. Add "Allow: /" in production
2. The production flag doesn't get tripped somehow, so figure out why not

**Comment by var-kyle** [comment]
My understanding was that the `Allow` keyword was Google specific and that
```
User-agent: *
Disallow: 
```
is equivalent to
```
User-agent: *
Allow: /
```
So by checking https://alpha.service.canada.ca/robots.txt (it displays the correct file now), it shows
```
User-agent: *
Disallow: /api/*
```
Which should mean that only the api routes are disallowed and all other routes are allowed.

**Comment by pcraig3** [comment]
I looked it up and you're right. Not having any other rules is implicitly an `Allow: *` instruction, according to some blog I read.

One thing though: that rule you have doesn't explicitly disallow the `/api` route, only subdomains. [So hitting `/api` itself is allowed](https://en.ryte.com/free-tools/robots-txt/?refresh=1&url=https%3A%2F%2Falpha.service.canada.ca%2Fapi&useragent=Googlebot&submit=Evaluate).

<img width="391" alt="Screen Shot 2021-08-05 at 09 37 49" src="https://user-images.githubusercontent.com/2454380/128359257-c1ade5dc-e3a5-4d8e-b3b8-c648eff5322e.png">

In practice, it doesn't seem to matter, as the "/api" route is a 404 and search engines obviously don't index routes that are 404s.

So, fair enough. I will close the issue.

**Comment by var-kyle** [comment]
You are right that I should have used `Disallow: /api` instead of `Disallow: /api/*`. I might create a PR to address this, but it's not a priority.
