### ISSUE TITLE
Improvements to the Report a Problem widget

### ISSUE THREAD

**Issue by pcraig3** [DTS-STN/Alpha-Site#42]
It's pretty good, but there's a number of fixes that we should make

| desktop | mobile |
|---------|--------|
|  Our widget on [alphasite-main.dev.dts-stn.com](https://alphasite-main.dev.dts-stn.com/)    |  Widget on [Canada.ca Design System](https://design.canada.ca/common-design-patterns/report-problem.html)      |
|  <img width="312" alt="Screen Shot 2021-04-22 at 08 54 34" src="https://user-images.githubusercontent.com/2454380/115717998-b71c7380-a348-11eb-80c1-91b92e57d065.png">   |  <img width="350" alt="Screen Shot 2021-04-22 at 08 54 45" src="https://user-images.githubusercontent.com/2454380/115718007-b84da080-a348-11eb-8ae8-d9ba79a0c257.png">   |

### Report a problem `<summary>` element
- "Report a problem on this page"
- Text should be centred
- Text should be blue (like a link)
- Cursor should be a `pointer` when hovered  
- Active state should have a darker background
- They are using `border-style: outset` to make it "pop"

### Groups of checkboxes 
- Groups of related checkboxes / radio buttons should always be inside a `<fieldset>`: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/fieldset
- The "check all the issues" text should be the `<legend>` for the fieldset (so, inside of the `<form>`)

### Checkboxes
- Let's make them 40 by 40px, not 44 by 44px
-  Remove 2px `top` and `left` CSS on input
- Set label:before `background` to `white`
- Set label:after `height` to 13px

### Font sizing
- 12px is way too small: let's set it to 16px again
- Line height should be `1.4` or `1.5`
- The "check all the issues" text at 18px is not enough contrast to 16px font, so increase it to 20 or 22px and increase the bottom margin a bit

### Width 
- Setting 300px seems tight to me. Can we set a `max-width` of 350-400 somewhere (maybe 380?) and then `width: 100%` so that it will size down as needed.

Maybe there's a bit more, but that will help a lot.

**Comment by pcraig3** [comment]
The Life Journeys one has a pretty good `summary` implementation, here's a gif

![Screen Recording 2021-04-22 at 09 57 50](https://user-images.githubusercontent.com/2454380/115727273-7117dd80-a351-11eb-91ed-44c0d35e53ba.gif)

**Comment by Moro-Code** [comment]
Solved by #43
