### ISSUE TITLE
"Incorrect Information" appears twice in the Report a problem widget

### ISSUE THREAD

**Issue by pcraig3** [DTS-STN/Alpha-Site#84]
Just something I didn't notice earlier. Inside the Report a Problem widget, we've included "Incorrect Information" as the first option **and** the fifth option. Obviously, we should remove one of them.

<img width="364" alt="Screen Shot 2021-06-01 at 10 49 56" src="https://user-images.githubusercontent.com/2454380/120344056-39447400-c2c7-11eb-8eea-f6bcee0ce45e.png">

**Comment by Moro-Code** [comment]
Falce palm 🤦🏽‍♂️... sorry about that
