### ISSUE TITLE
Report a problem widget can be submitted without entering any data

### ISSUE THREAD

**Issue by pcraig3** [DTS-STN/Alpha-Site#85]
If you load the homepage of the Alpha site, open the Report a problem widget, and then "submit" it, you will get a thank you message.

This isn't clearly a problem. If we wanted to keep this behaviour, it's fine, but I do think it's worth highlighting.

From my perspective, the options are:

1. Say thank you for your response, and send a blank email
2. Say thank you for your response, but don't send an email
3. Include some kind of form validation (error! you must enter something!), and don't send an email

I think we should do 2, or 3.

Trying this out on [the Canada.ca homepage](https://www.canada.ca/en.html), you are also able to submit the report a problem widget without entering any data, so we could just take this as precedent and stick with 2.

**Comment by Moro-Code** [comment]
I think is fine behaviour... emails are only sent on the API side of things if there is data. We don't really have any way in the designs to inform the user that they must select at least one.
